### ISSUE TITLE
Add more contrast at code blocks?

### ISSUE THREAD

**Issue by cddesja** [vbuzin/berrys-theme#2]
This theme is excellent and is definitely my favorite light theme and I was curious if it might be possible to add a contrasting background to lines that start with #+BEGIN_SRC and #+END_SRC? Similar to but not as jarring as the leuven theme?

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/1608939/74545179-67594580-4f16-11ea-8170-9b9d04d89ef4.png">

**Comment by vbuzin** [comment]
Thanks for the feedback. When making the theme I tried to avoid using background colours. It's a matter of preference, of course, but I would rather keep it as it is. However, you can easily adjust it to your needs. Just clone the repo, add the following to `berrys-theme.el` and enjoy your new src block background. 

```
   `(org-block-begin-line ((,class (:background ,berrys04))))
   `(org-block-end-line ((,class (:background ,berrys04))))
```
or use your own colours:

```
   `(org-block-begin-line ((,class (:background "#FA5D66"))))
   `(org-block-end-line ((,class (:background "#66F446"))))
```

Here's how to load the theme from disk instead of melpa. 

```
(use-package berrys-theme
  :ensure nil
  :init
  (add-to-list 'custom-theme-load-path "~/Projects/berrys-theme")
  (load-theme 'berrys t))
```
